//A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
//Input : abc
//Output : a, b, c, ab, bc, ac, abc
package Strings;

public class PrintAllSubsequence {
    public static void main(String[] args) {
        String str =  "abc";
        PrintAllSubsequence obj = new PrintAllSubsequence();
        obj.approach1(str,0,"");
    }

    //using recurssion: pick and dont pick
    // time = 2^n, space = stack space n
    private void approach1(String str, int indx, String ans) {
        if(indx==str.length()){
            System.out.print(ans+", ");
            return;
        }
        approach1(str, indx+1, ans+str.charAt(indx));
        approach1(str, indx+1, ans);
    }
}
